### ISSUE TITLE
How it works the real-time search?

### ISSUE THREAD

**Issue by TommyB1992** [Agnar22/Pluribus#1]
I'm surprised that I am the only one who saw this code and thank you, you saved my life (can I offer you something?) because I have reimplemented it.
I understand how mccfr works pretty much well but I don't understand how real-time search works. Is it used lcfr for that?
I thought that the only reasonable way of doing that is to use the pre-trained regrets and sets the hero game steps fixed for one player.

For example, if the action is:
- sb/bb: 1/2$
- Player 1 raises 4$
- Player 2 calls 2$
Flop:
- Player 2 checks
- Player 1 bets 6$
- Player 2 raises 18$
- no solution

Then in the lcfr (?) do I have to set fixed this first actions for n° time iterations?

**Comment by agnarbjoernstad** [comment]
Great! So good to hear.

The real-time search is not yet implemented in this repository. The [supplementary material](https://www.science.org/doi/suppl/10.1126/science.aay2400/suppl_file/aay2400-brown-sm.pdf) to the [Pluribus paper](https://www.science.org/doi/10.1126/science.aay2400) has a thorough explanation of the real time search.

A section in the supplementary meterial states that: 
> Pluribus used one of two different forms of CFR to compute a strategy in the subgame
depending on the size of the subgame and the part of the game. If the subgame is relatively
large or it is early in the game, then Monte Carlo Linear CFR is used just as it was for the
blueprint strategy computation. Otherwise, Pluribus uses an optimized vector-based form of Linear CFR (38) that samples one set of public board cards per thread (42).

So yes, lcfr is used for real time search in some cases.

Directly preceding the section above:
>  Whenever a round ends, Pluribus makes the public state at the start of the new round the root of
the new subgame. It also updates its belief distribution for each player’s possible private cards
using Bayes’ rule based on strategy profile σ, where σ is the blueprint if real-time search has
not yet been conducted; otherwise σ is the output of the previously-run search.
If search is being done on the first betting round, then the subgame extends to the end of
the round, with leaf nodes at the chance nodes at the start of the second round. If search is
being done on the second betting round and there were more than two players at the start of the
round, then leaf nodes occur either at the chance nodes at the stat of the third betting round or
immediately after the second raise action, whichever is earlier. In all other cases, the subgame
extends to the end of the game.

For your example, this means that the root of the real time search would be after the flop.
